name: MacOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_compilers_gcc:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ 11, 12, 13 ]
        preset: [ 'macos-release-user' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up codebase
        uses: ./.github/actions/setup-codebase
      - name: Install dependencies
        run: brew install gcc@${{ matrix.compiler }}
      - name: Make and test
        uses: ./.github/actions/make-and-test
        with:
          preset: ${{ matrix.preset }}

  test_compilers_clang:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ 16 ]
        preset: [ 'macos-release-user' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up codebase
        uses: ./.github/actions/setup-codebase
      - name: Install dependencies
        run: |
          brew install clang@${{ matrix.compiler }}
          export CC=/opt/homebrew/opt/llvm/bin/clang
          export CXX=/opt/homebrew/opt/llvm/bin/clang++
      - name: Make and test
        uses: ./.github/actions/make-and-test
        with:
          preset: ${{ matrix.preset }}
