name: MacOS Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_compilers_gcc:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ 11, 12, 13, 14 ]
        preset: [ 'macos-release-user' ]
    steps:
      - name: Set up codebase
        uses: refvalue/setup-codebase-action@main
        with:
          shell: bash
      - name: Install dependencies
        run: |
          brew install gcc@${{ matrix.compiler }}
          export CC=gcc
          export CXX=g++
      - name: Make and test
        uses: refvalue/make-and-test-action@main
        with:
          preset: ${{ matrix.preset }}
          shell: bash

  test_compilers_clang:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ 17 ]
        preset: [ 'macos-release-user' ]
    steps:
      - name: Set up codebase
        uses: refvalue/setup-codebase-action@main
        with:
          shell: bash
      - name: Install dependencies
        run: |
          brew install llvm@${{ matrix.compiler }}
          export CC=/opt/homebrew/opt/llvm/bin/clang
          export CXX=/opt/homebrew/opt/llvm/bin/clang++
      - name: Make and test
        uses: refvalue/make-and-test-action@main
        with:
          preset: ${{ matrix.preset }}
          shell: bash
