name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_compilers_msvc:
    runs-on: windows-2022
    strategy:
      matrix:
        preset: [ 'windows-debug-user', 'windows-release-user' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up codebase
        uses: ./.github/actions/setup-codebase
        with:
          shell: pwsh
      - name: Make and test
        uses: ./.github/actions/make-and-test
        with:
          preset: ${{ matrix.preset }}
          shell: bash
