name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_compilers_msvc:
    runs-on: windows-2022
    strategy:
      matrix:
        preset: [ 'windows-debug-user', 'windows-release-user' ]
    steps:
      - name: Set up codebase
        uses: refvalue/setup-codebase-action
        with:
          shell: pwsh
      - name: Make and test
        uses: refvalue/make-and-test-action
        with:
          preset: ${{ matrix.preset }}
          shell: pwsh
